server:
  port: 8081 # 服务端口

spring:
  application:
    name: video-platform
  datasource:
    # ???????
    url: jdbc:mysql://localhost:3306/video_platform
    username: root  # ??MySQL??????root
    password: 123456789  # ?????????????MySQL????????????
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # JPA ??
    hibernate:
      ddl-auto: update # ???????????????????????
    show-sql: true # ??????SQL???????
    properties:
      hibernate:
        format_sql: true # ???SQL????
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 10000MB # 单个文件最大限制
      max-request-size: 10000MB